# Generated by Django 6.0.3 on 2026-05-09 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField(default='https://images.unsplash.com/photo-1517248135467-4c7edcad34c4', max_length=400)),
                ('cover_image', models.URLField(default='https://images.unsplash.com/photo-1517248135467-4c7edcad34c4', max_length=400)),
                ('cuisine', models.CharField(max_length=200)),
                ('price_for_two', models.IntegerField(default=1000)),
                ('dining_offer', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('opening_time', models.TimeField(default='10:00:00')),
                ('closing_time', models.TimeField(default='23:00:00')),
                ('total_tables', models.IntegerField(default=10)),
                ('dining_enabled', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=4.0)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('ambience_tags', models.CharField(default='Fine Dining, Romantic', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DiningOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_bill', models.IntegerField(default=0)),
                ('discount_percent', models.IntegerField(default=10)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dining_offers', to='delivery.diningrestaurant')),
            ],
        ),
        migrations.CreateModel(
            name='DiningTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=20)),
                ('seats', models.IntegerField(default=2)),
                ('availability', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='delivery.diningrestaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('guests', models.IntegerField(default=2)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='confirmed', max_length=20)),
                ('special_request', models.TextField(blank=True, null=True)),
                ('occasion', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='delivery.diningrestaurant')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='delivery.diningtable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='delivery.customer')),
            ],
        ),
    ]
