# Generated by Django 6.0.3 on 2026-05-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_diningrestaurant_diningoffer_diningtable_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('cover_image', models.URLField(blank=True, max_length=400, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('theme_color', models.CharField(default='#eab308', max_length=20)),
                ('display_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='diningoffer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='diningoffer',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diningoffer',
            name='max_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diningoffer',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diningoffer',
            name='valid_till',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diningrestaurant',
            name='ambience_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diningrestaurant',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diningrestaurant',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diningrestaurant',
            name='gallery_images',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diningrestaurant',
            name='kids_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diningrestaurant',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diningrestaurant',
            name='live_music',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diningrestaurant',
            name='logo',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='diningrestaurant',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diningrestaurant',
            name='outdoor_seating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diningrestaurant',
            name='pet_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diningrestaurant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='diningrestaurant',
            name='pure_veg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diningrestaurant',
            name='rooftop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diningrestaurant',
            name='serves_alcohol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diningrestaurant',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='diningrestaurant',
            name='smoking_zone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diningrestaurant',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diningrestaurant',
            name='trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diningrestaurant',
            name='valet_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diningrestaurant',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='delivery.diningcategory'),
        ),
        migrations.CreateModel(
            name='DiningCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('banner_image', models.URLField(blank=True, max_length=400, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('collection_type', models.CharField(blank=True, max_length=50, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('restaurants', models.ManyToManyField(blank=True, related_name='collections', to='delivery.diningrestaurant')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
